name: DayPLanner CI

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build_and_test_multiplatform:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'

      - name: build
        run: |
          mkdir build
          cd build
          if [ $RUNNER_OS == 'Windows' ]; then
            cmake .. -DCMAKE_PREFIX_PATH="${QT_INSTALL_DIR}/6.5.*\\win64" -DQt6_DIR="${QT_INSTALL_DIR}/6.5.0\\win64" -G "Visual Studio 17 2022"
          else
            cmake .. -DCMAKE_PREFIX_PATH="${QT_INSTALL_DIR}/6.5.*/clang_64" -DQt6_DIR="${QT_INSTALL_DIR}/6.5.0/clang_64"

          cmake --build .

      - name: test
        run: |
          cd ./build
          ctest